# Generated by Django 5.0.3 on 2024-03-30 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('village_name', models.CharField(max_length=20)),
                ('tehsil', models.CharField(max_length=20)),
                ('district', models.CharField(max_length=20)),
                ('population', models.IntegerField()),
                ('village_head', models.CharField(max_length=20)),
            ],
        ),
    ]
